# Generated by Django 4.2.2 on 2023-07-11 23:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mascotitas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boleta",
            fields=[
                ("id_boleta", models.AutoField(primary_key=True, serialize=False)),
                ("total", models.BigIntegerField()),
                ("fechaCompra", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Mercancia",
            fields=[
                (
                    "nombre",
                    models.CharField(
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Descripcion"
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=8)),
                ("stock", models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="animal",
            name="nombre",
            field=models.CharField(
                max_length=15, primary_key=True, serialize=False, verbose_name="Nombre"
            ),
        ),
        migrations.CreateModel(
            name="detalle_boleta",
            fields=[
                (
                    "id_detalle_boleta",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cantidad", models.IntegerField()),
                ("subtotal", models.BigIntegerField()),
                (
                    "id_boleta",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mascotitas.boleta",
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mascotitas.mercancia",
                    ),
                ),
            ],
        ),
    ]
