# Generated by Django 4.2.2 on 2023-07-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mascotitas", "0002_boleta_mercancia_alter_animal_nombre_detalle_boleta"),
    ]

    operations = [
        migrations.AddField(
            model_name="mercancia",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="imagenes", verbose_name="Imagen"
            ),
        ),
    ]
