# Generated by Django 4.2.2 on 2023-07-12 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mascotitas", "0003_mercancia_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="mercancia",
            name="especie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mascotitas.especie",
                verbose_name="Especie",
            ),
            preserve_default=False,
        ),
    ]
