# Generated by Django 4.2.2 on 2023-07-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotitas', '0004_mercancia_especie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especie',
            old_name='idEspecia',
            new_name='idEspecie',
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
