# Generated by Django 4.2.3 on 2023-07-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotitas', '0005_rename_idespecia_especie_idespecie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='envio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boleta',
            name='total_imp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalle_boleta',
            name='subtotal_imp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
